-- Nouveau depart des questions par modes.
-- A lancer apres supabase/schema.sql.
-- Supprime les anciennes questions, votes et scores, puis insere 14 modes de 25 questions.

delete from public.scores;
delete from public.votes;
delete from public.questions;

update public.players
set xp = 0,
    level = 1;

insert into public.questions (id, category, question, choice_a, choice_b) values
('food_001', 'food', 'Tu dois choisir un plat pour un repas parfait :', 'Pizza margherita', 'Burger maison'),
('food_002', 'food', 'Tu dois choisir un plat pour une soiree entre amis :', 'Raclette', 'Fondue savoyarde'),
('food_003', 'food', 'Tu dois choisir un plaisir rapide :', 'Kebab', 'Tacos francais'),
('food_004', 'food', 'Tu dois choisir un plat qui met tout le monde d''accord :', 'Sushis', 'Pates carbonara'),
('food_005', 'food', 'Tu dois choisir un dessert de comfort food :', 'Crepes sucrees', 'Gaufres croustillantes'),
('food_006', 'food', 'Tu dois choisir un snack sale :', 'Nuggets', 'Frites'),
('food_007', 'food', 'Tu dois choisir un petit-dejeuner :', 'Pain au chocolat', 'Croissant'),
('food_008', 'food', 'Tu dois choisir une sauce pour tout accompagner :', 'Sauce algerienne', 'Sauce barbecue'),
('food_009', 'food', 'Tu dois choisir une envie sucree :', 'Nutella', 'Confiture de fraise'),
('food_010', 'food', 'Tu dois choisir un plat de dimanche :', 'Lasagnes', 'Poulet roti'),
('food_011', 'food', 'Tu dois choisir une cuisine du monde :', 'Cuisine japonaise', 'Cuisine mexicaine'),
('food_012', 'food', 'Tu dois choisir une pause fraiche :', 'Glace vanille', 'Sorbet citron'),
('food_013', 'food', 'Tu dois choisir une boisson de repas :', 'Coca-Cola', 'Ice tea'),
('food_014', 'food', 'Tu dois choisir un plat de fete :', 'Paella', 'Couscous'),
('food_015', 'food', 'Tu dois choisir un fromage :', 'Camembert', 'Comte'),
('food_016', 'food', 'Tu dois choisir un dessert classique :', 'Tiramisu', 'Mousse au chocolat'),
('food_017', 'food', 'Tu dois choisir une commande tard le soir :', 'Wrap poulet', 'Panini fromage'),
('food_018', 'food', 'Tu dois choisir un plat simple mais efficace :', 'Omelette', 'Quiche lorraine'),
('food_019', 'food', 'Tu dois choisir une gourmandise :', 'Bonbons acidules', 'Chocolat au lait'),
('food_020', 'food', 'Tu dois choisir un plat qui cale vraiment :', 'Gratin dauphinois', 'Hachis parmentier'),
('food_021', 'food', 'Tu dois choisir une recette de plage :', 'Salade Caesar', 'Sandwich jambon-beurre'),
('food_022', 'food', 'Tu dois choisir une commande fast-food :', 'Menu McDo', 'Menu Burger King'),
('food_023', 'food', 'Tu dois choisir un plat reconfortant :', 'Soupe a l''oignon', 'Raviolis'),
('food_024', 'food', 'Tu dois choisir un apero :', 'Chips paprika', 'Olives vertes'),
('food_025', 'food', 'Tu dois choisir un dessert d''enfance :', 'Flan patissier', 'Ile flottante'),

('movies_001', 'movies', 'Tu dois choisir un film culte a revoir maintenant :', 'Harry Potter', 'Star Wars'),
('movies_002', 'movies', 'Tu dois choisir un film connu par coeur :', 'Titanic', 'Avatar'),
('movies_003', 'movies', 'Tu dois choisir un film d''animation culte :', 'Shrek', 'Toy Story'),
('movies_004', 'movies', 'Tu dois choisir une saga populaire :', 'Fast and Furious', 'Avengers'),
('movies_005', 'movies', 'Tu dois choisir un Disney culte :', 'Le Roi Lion', 'Aladdin'),
('movies_006', 'movies', 'Tu dois choisir un film d''aventure :', 'Jurassic Park', 'Indiana Jones'),
('movies_007', 'movies', 'Tu dois choisir une comedie francaise :', 'Intouchables', 'Bienvenue chez les Ch''tis'),
('movies_008', 'movies', 'Tu dois choisir un super-heros au cinema :', 'Spider-Man', 'Batman'),
('movies_009', 'movies', 'Tu dois choisir un film de science-fiction :', 'Retour vers le futur', 'Matrix'),
('movies_010', 'movies', 'Tu dois choisir une saga fantastique :', 'Le Seigneur des Anneaux', 'Pirates des Caraibes'),
('movies_011', 'movies', 'Tu dois choisir un film culte sombre :', 'Joker', 'Fight Club'),
('movies_012', 'movies', 'Tu dois choisir un film a suspens :', 'Inception', 'Shutter Island'),
('movies_013', 'movies', 'Tu dois choisir une comedie americaine :', 'Very Bad Trip', 'Maman j''ai rate l''avion'),
('movies_014', 'movies', 'Tu dois choisir un film d''action :', 'Mission Impossible', 'John Wick'),
('movies_015', 'movies', 'Tu dois choisir un film romantique :', 'La La Land', 'Nos etoiles contraires'),
('movies_016', 'movies', 'Tu dois choisir une saga magique :', 'Les Animaux fantastiques', 'Narnia'),
('movies_017', 'movies', 'Tu dois choisir un film de robots :', 'Transformers', 'Terminator'),
('movies_018', 'movies', 'Tu dois choisir un film de survie :', 'Seul au monde', 'The Revenant'),
('movies_019', 'movies', 'Tu dois choisir un film francais culte :', 'Les Visiteurs', 'Asterix Mission Cleopatre'),
('movies_020', 'movies', 'Tu dois choisir un film d''horreur connu :', 'Scream', 'Conjuring'),
('movies_021', 'movies', 'Tu dois choisir un film de guerre culte :', 'Il faut sauver le soldat Ryan', 'Dunkerque'),
('movies_022', 'movies', 'Tu dois choisir un film avec des courses :', 'Cars', 'Need for Speed'),
('movies_023', 'movies', 'Tu dois choisir une grande aventure familiale :', 'Jumanji', 'Charlie et la chocolaterie'),
('movies_024', 'movies', 'Tu dois choisir un film d''espionnage :', 'James Bond', 'Kingsman'),
('movies_025', 'movies', 'Tu dois choisir un film musical :', 'The Greatest Showman', 'Grease'),

('series_001', 'series', 'Tu dois choisir une serie a lancer ce soir :', 'Stranger Things', 'Mercredi'),
('series_002', 'series', 'Tu dois choisir une serie de phenomene mondial :', 'Squid Game', 'La Casa de Papel'),
('series_003', 'series', 'Tu dois choisir une serie intense :', 'Breaking Bad', 'The Walking Dead'),
('series_004', 'series', 'Tu dois choisir une sitcom culte :', 'Friends', 'How I Met Your Mother'),
('series_005', 'series', 'Tu dois choisir une serie epique :', 'Game of Thrones', 'Vikings'),
('series_006', 'series', 'Tu dois choisir un anime long :', 'Naruto', 'One Piece'),
('series_007', 'series', 'Tu dois choisir une serie de super-heros :', 'The Boys', 'Daredevil'),
('series_008', 'series', 'Tu dois choisir une serie policiere :', 'Sherlock', 'Mentalist'),
('series_009', 'series', 'Tu dois choisir une serie nostalgique :', 'Malcolm', 'Les Simpson'),
('series_010', 'series', 'Tu dois choisir une serie medicale :', 'Grey''s Anatomy', 'Dr House'),
('series_011', 'series', 'Tu dois choisir une serie fantastique :', 'The Witcher', 'Shadow and Bone'),
('series_012', 'series', 'Tu dois choisir une serie de braquage :', 'Prison Break', 'Lupin'),
('series_013', 'series', 'Tu dois choisir une serie sombre :', 'Black Mirror', 'Dark'),
('series_014', 'series', 'Tu dois choisir une serie comique :', 'Brooklyn Nine-Nine', 'The Office'),
('series_015', 'series', 'Tu dois choisir une serie ado :', 'Elite', 'Sex Education'),
('series_016', 'series', 'Tu dois choisir une serie d''animation adulte :', 'Rick and Morty', 'South Park'),
('series_017', 'series', 'Tu dois choisir une serie de zombies :', 'The Last of Us', 'All of Us Are Dead'),
('series_018', 'series', 'Tu dois choisir une serie judiciaire :', 'Suits', 'Better Call Saul'),
('series_019', 'series', 'Tu dois choisir une serie de mystere :', 'Lost', 'Manifest'),
('series_020', 'series', 'Tu dois choisir une serie francaise :', 'HPI', 'Dix pour cent'),
('series_021', 'series', 'Tu dois choisir une serie historique :', 'The Crown', 'Peaky Blinders'),
('series_022', 'series', 'Tu dois choisir une serie familiale :', 'Modern Family', 'Desperate Housewives'),
('series_023', 'series', 'Tu dois choisir une serie de fantasy :', 'House of the Dragon', 'Rings of Power'),
('series_024', 'series', 'Tu dois choisir une serie de competition :', 'Koh-Lanta', 'Top Chef'),
('series_025', 'series', 'Tu dois choisir une serie teen culte :', 'Riverdale', 'Gossip Girl'),

('games_001', 'games', 'Tu dois choisir un jeu video pour jouer toute la nuit :', 'Minecraft', 'Fortnite'),
('games_002', 'games', 'Tu dois choisir un jeu d''action culte :', 'GTA V', 'Call of Duty'),
('games_003', 'games', 'Tu dois choisir un jeu entre amis :', 'Mario Kart', 'Super Smash Bros'),
('games_004', 'games', 'Tu dois choisir une grande licence Nintendo :', 'Zelda', 'Pokemon'),
('games_005', 'games', 'Tu dois choisir un jeu competitif :', 'Valorant', 'Counter-Strike'),
('games_006', 'games', 'Tu dois choisir un jeu de sport :', 'EA Sports FC', 'NBA 2K'),
('games_007', 'games', 'Tu dois choisir un monde ouvert :', 'Red Dead Redemption 2', 'Cyberpunk 2077'),
('games_008', 'games', 'Tu dois choisir un jeu de survie :', 'Subnautica', 'ARK'),
('games_009', 'games', 'Tu dois choisir un jeu mobile connu :', 'Clash Royale', 'Brawl Stars'),
('games_010', 'games', 'Tu dois choisir un jeu creatif :', 'Roblox', 'Les Sims'),
('games_011', 'games', 'Tu dois choisir un jeu de course :', 'Forza Horizon', 'Gran Turismo'),
('games_012', 'games', 'Tu dois choisir un jeu difficile :', 'Dark Souls', 'Elden Ring'),
('games_013', 'games', 'Tu dois choisir un jeu narratif :', 'The Last of Us', 'Life is Strange'),
('games_014', 'games', 'Tu dois choisir un jeu d''horreur :', 'Resident Evil', 'Five Nights at Freddy''s'),
('games_015', 'games', 'Tu dois choisir un jeu de construction :', 'Cities Skylines', 'Planet Coaster'),
('games_016', 'games', 'Tu dois choisir un jeu de ferme :', 'Stardew Valley', 'Animal Crossing'),
('games_017', 'games', 'Tu dois choisir un hero shooter :', 'Overwatch', 'Apex Legends'),
('games_018', 'games', 'Tu dois choisir un jeu retro :', 'Pac-Man', 'Tetris'),
('games_019', 'games', 'Tu dois choisir un jeu de combat :', 'Tekken', 'Street Fighter'),
('games_020', 'games', 'Tu dois choisir une aventure PlayStation :', 'God of War', 'Uncharted'),
('games_021', 'games', 'Tu dois choisir un jeu de plateforme :', 'Sonic', 'Crash Bandicoot'),
('games_022', 'games', 'Tu dois choisir un jeu de strategie :', 'Age of Empires', 'Clash of Clans'),
('games_023', 'games', 'Tu dois choisir un jeu d''exploration :', 'No Man''s Sky', 'Hollow Knight'),
('games_024', 'games', 'Tu dois choisir un jeu de rythme :', 'Just Dance', 'Guitar Hero'),
('games_025', 'games', 'Tu dois choisir un jeu party game :', 'Among Us', 'Fall Guys'),

('music_001', 'music', 'Tu dois choisir un style de musique pour une soiree :', 'Rap', 'Pop'),
('music_002', 'music', 'Tu dois choisir une ambiance :', 'Electro', 'Reggaeton'),
('music_003', 'music', 'Tu dois choisir un artiste francophone :', 'Stromae', 'Orelsan'),
('music_004', 'music', 'Tu dois choisir une diva pop :', 'Taylor Swift', 'Ariana Grande'),
('music_005', 'music', 'Tu dois choisir un moment musical :', 'Concert', 'Festival'),
('music_006', 'music', 'Tu dois choisir une plateforme :', 'Spotify', 'YouTube Music'),
('music_007', 'music', 'Tu dois choisir une facon d''ecouter :', 'Casque audio', 'Enceinte Bluetooth'),
('music_008', 'music', 'Tu dois choisir une vibe ancienne :', 'Rock classique', 'Disco'),
('music_009', 'music', 'Tu dois choisir un instrument star :', 'Guitare electrique', 'Piano'),
('music_010', 'music', 'Tu dois choisir un style pour danser :', 'Afrobeat', 'Dancehall'),
('music_011', 'music', 'Tu dois choisir une battle rap :', 'Booba', 'Kaaris'),
('music_012', 'music', 'Tu dois choisir un hitmaker :', 'Ninho', 'Jul'),
('music_013', 'music', 'Tu dois choisir une artiste francaise :', 'Aya Nakamura', 'Angele'),
('music_014', 'music', 'Tu dois choisir une musique de trajet :', 'Playlist chill', 'Playlist motivation'),
('music_015', 'music', 'Tu dois choisir un format :', 'Album complet', 'Singles en boucle'),
('music_016', 'music', 'Tu dois choisir une epoque :', 'Annees 80', 'Annees 2000'),
('music_017', 'music', 'Tu dois choisir un son de fete :', 'DJ set', 'Karaoke'),
('music_018', 'music', 'Tu dois choisir une musique calme :', 'Lo-fi', 'Jazz'),
('music_019', 'music', 'Tu dois choisir une musique intense :', 'Metal', 'Drill'),
('music_020', 'music', 'Tu dois choisir un clip :', 'Clip choregraphie', 'Clip narratif'),
('music_021', 'music', 'Tu dois choisir un support :', 'Vinyle', 'Streaming'),
('music_022', 'music', 'Tu dois choisir un duo :', 'Dua Lipa', 'Billie Eilish'),
('music_023', 'music', 'Tu dois choisir un moment :', 'Musique sous la douche', 'Musique en voiture'),
('music_024', 'music', 'Tu dois choisir une voix :', 'Voix puissante', 'Voix douce'),
('music_025', 'music', 'Tu dois choisir une decouverte :', 'Artiste inconnu', 'Tube populaire'),

('social_001', 'social', 'Tu dois choisir une appli pour une semaine :', 'TikTok', 'Instagram'),
('social_002', 'social', 'Tu dois choisir une plateforme video :', 'YouTube', 'Netflix'),
('social_003', 'social', 'Tu dois choisir une messagerie :', 'Discord', 'WhatsApp'),
('social_004', 'social', 'Tu dois choisir un format court :', 'Reels', 'Shorts'),
('social_005', 'social', 'Tu dois choisir une facon de poster :', 'Story', 'Publication'),
('social_006', 'social', 'Tu dois choisir une reaction :', 'Like', 'Commentaire'),
('social_007', 'social', 'Tu dois choisir un style de message :', 'Vocal', 'Texte'),
('social_008', 'social', 'Tu dois choisir une notification :', 'Nouveau follow', 'Nouveau message'),
('social_009', 'social', 'Tu dois choisir un reseau a supprimer :', 'Snapchat', 'Facebook'),
('social_010', 'social', 'Tu dois choisir une habitude :', 'Scroller avant de dormir', 'Scroller au reveil'),
('social_011', 'social', 'Tu dois choisir un profil :', 'Compte prive', 'Compte public'),
('social_012', 'social', 'Tu dois choisir une tendance :', 'Meme viral', 'Danse virale'),
('social_013', 'social', 'Tu dois choisir une bio :', 'Bio mysterieuse', 'Bio drole'),
('social_014', 'social', 'Tu dois choisir un filtre :', 'Filtre naturel', 'Filtre absurde'),
('social_015', 'social', 'Tu dois choisir un groupe :', 'Groupe amis', 'Groupe famille'),
('social_016', 'social', 'Tu dois choisir une visibilite :', 'Vu par tout le monde', 'Vu par proches amis'),
('social_017', 'social', 'Tu dois choisir un live :', 'Live gaming', 'Live discussion'),
('social_018', 'social', 'Tu dois choisir une reaction rapide :', 'Emoji', 'Sticker'),
('social_019', 'social', 'Tu dois choisir un compte a suivre :', 'Humour', 'Actualites'),
('social_020', 'social', 'Tu dois choisir un contenu :', 'Vlog', 'Tutoriel'),
('social_021', 'social', 'Tu dois choisir un appareil :', 'Telephone', 'Ordinateur'),
('social_022', 'social', 'Tu dois choisir une interaction :', 'DM', 'Appel video'),
('social_023', 'social', 'Tu dois choisir une archive :', 'Photos anciennes', 'Messages anciens'),
('social_024', 'social', 'Tu dois choisir un statut :', 'En ligne visible', 'Invisible'),
('social_025', 'social', 'Tu dois choisir une page a garder :', 'Pour toi', 'Abonnements'),

('love_001', 'love', 'Tu dois choisir une situation amoureuse :', 'Etre quitte par message', 'Etre ghoste'),
('love_002', 'love', 'Tu dois choisir un premier rendez-vous :', 'Restaurant', 'Cinema'),
('love_003', 'love', 'Tu dois choisir un style de couple :', 'Couple fusionnel', 'Couple independant'),
('love_004', 'love', 'Tu dois choisir une verite difficile :', 'Dire la verite blessante', 'Mentir pour proteger'),
('love_005', 'love', 'Tu dois choisir un obstacle :', 'Relation a distance', 'Vivre ensemble trop vite'),
('love_006', 'love', 'Tu dois choisir une preuve d''amour :', 'Grand geste public', 'Petit geste quotidien'),
('love_007', 'love', 'Tu dois choisir une qualite :', 'Humour', 'Fidelite'),
('love_008', 'love', 'Tu dois choisir une discussion :', 'Parler du futur', 'Parler du passe'),
('love_009', 'love', 'Tu dois choisir une peur :', 'Jalousie', 'Routine'),
('love_010', 'love', 'Tu dois choisir une surprise :', 'Week-end improvise', 'Cadeau personnalise'),
('love_011', 'love', 'Tu dois choisir une erreur :', 'Oublier un anniversaire', 'Lire un message prive'),
('love_012', 'love', 'Tu dois choisir un date simple :', 'Balade de nuit', 'Cafe en terrasse'),
('love_013', 'love', 'Tu dois choisir un compliment :', 'Tu me fais rire', 'Je me sens bien avec toi'),
('love_014', 'love', 'Tu dois choisir une rupture :', 'Rupture propre', 'Rupture floue'),
('love_015', 'love', 'Tu dois choisir une rencontre :', 'Ami d''ami', 'Appli de rencontre'),
('love_016', 'love', 'Tu dois choisir une dispute :', 'Silence froid', 'Discussion explosive'),
('love_017', 'love', 'Tu dois choisir une promesse :', 'Toujours honnete', 'Toujours present'),
('love_018', 'love', 'Tu dois choisir une attention :', 'Message du matin', 'Appel du soir'),
('love_019', 'love', 'Tu dois choisir un couple ideal :', 'Passion intense', 'Paix durable'),
('love_020', 'love', 'Tu dois choisir une limite :', 'Pas de mensonge', 'Pas de secret'),
('love_021', 'love', 'Tu dois choisir une preuve de confiance :', 'Donner son telephone', 'Partager ses doutes'),
('love_022', 'love', 'Tu dois choisir un souvenir :', 'Premier baiser', 'Premier voyage'),
('love_023', 'love', 'Tu dois choisir une compatibilite :', 'Meme humour', 'Memes valeurs'),
('love_024', 'love', 'Tu dois choisir une declaration :', 'Je t''aime en premier', 'Attendre que l''autre le dise'),
('love_025', 'love', 'Tu dois choisir une fin :', 'Rester amis', 'Couper les ponts'),

('school_work_001', 'school_work', 'Tu dois choisir une galere :', 'Controle surprise', 'Expose oral'),
('school_work_002', 'school_work', 'Tu dois choisir un prof :', 'Prof strict mais juste', 'Prof sympa mais brouillon'),
('school_work_003', 'school_work', 'Tu dois choisir un rythme :', 'Se lever a 5h', 'Travailler de nuit'),
('school_work_004', 'school_work', 'Tu dois choisir un stage :', 'Stage passionnant non paye', 'Job ennuyeux bien paye'),
('school_work_005', 'school_work', 'Tu dois choisir une semaine :', '4 jours intenses', '5 jours tranquilles'),
('school_work_006', 'school_work', 'Tu dois choisir une pause :', 'Pause cafe', 'Pause dehors'),
('school_work_007', 'school_work', 'Tu dois choisir une mission :', 'Projet en groupe', 'Projet solo'),
('school_work_008', 'school_work', 'Tu dois choisir une pression :', 'Deadline courte', 'Objectif flou'),
('school_work_009', 'school_work', 'Tu dois choisir une reunion :', 'Reunion inutile', 'Mail trop long'),
('school_work_010', 'school_work', 'Tu dois choisir une matiere :', 'Maths', 'Francais'),
('school_work_011', 'school_work', 'Tu dois choisir un bureau :', 'Open space', 'Bureau ferme'),
('school_work_012', 'school_work', 'Tu dois choisir une sanction :', 'Retard note', 'Devoir double'),
('school_work_013', 'school_work', 'Tu dois choisir une presentation :', 'Parler devant 30 personnes', 'Envoyer un dossier parfait'),
('school_work_014', 'school_work', 'Tu dois choisir un chef :', 'Chef exigeant', 'Chef absent'),
('school_work_015', 'school_work', 'Tu dois choisir une recompense :', 'Augmentation', 'Plus de vacances'),
('school_work_016', 'school_work', 'Tu dois choisir une journee :', 'Journee productive', 'Journee sans stress'),
('school_work_017', 'school_work', 'Tu dois choisir un trajet :', '30 minutes de voiture', '45 minutes de transports'),
('school_work_018', 'school_work', 'Tu dois choisir une competence :', 'Parler en public', 'Ecrire parfaitement'),
('school_work_019', 'school_work', 'Tu dois choisir un examen :', 'QCM piegeux', 'Dissertation longue'),
('school_work_020', 'school_work', 'Tu dois choisir un collegue :', 'Tres competent mais froid', 'Tres sympa mais lent'),
('school_work_021', 'school_work', 'Tu dois choisir un planning :', 'Tout planifier', 'Improviser'),
('school_work_022', 'school_work', 'Tu dois choisir un lieu :', 'Teletravail', 'Bureau'),
('school_work_023', 'school_work', 'Tu dois choisir une erreur :', 'Rendre en retard', 'Rendre avec une faute visible'),
('school_work_024', 'school_work', 'Tu dois choisir une ambiance :', 'Equipe calme', 'Equipe bruyante'),
('school_work_025', 'school_work', 'Tu dois choisir un objectif :', 'Meilleur salaire', 'Meilleur equilibre de vie'),

('daily_001', 'daily', 'Tu dois choisir une contrainte du quotidien :', 'Toujours en retard', 'Toujours trop en avance'),
('daily_002', 'daily', 'Tu dois choisir une perte :', 'Perdre ses cles', 'Perdre son telephone'),
('daily_003', 'daily', 'Tu dois choisir une temperature :', 'Toujours trop chaud', 'Toujours trop froid'),
('daily_004', 'daily', 'Tu dois choisir un confort :', 'Lit parfait', 'Canape parfait'),
('daily_005', 'daily', 'Tu dois choisir un trajet :', 'Marcher sous la pluie', 'Attendre dans le froid'),
('daily_006', 'daily', 'Tu dois choisir une corvee :', 'Faire la vaisselle', 'Passer l''aspirateur'),
('daily_007', 'daily', 'Tu dois choisir un bug de vie :', 'Batterie a 1%', 'Wifi tres lent'),
('daily_008', 'daily', 'Tu dois choisir une habitude :', 'Douche le matin', 'Douche le soir'),
('daily_009', 'daily', 'Tu dois choisir un week-end :', 'Sortie improvisee', 'Repos total'),
('daily_010', 'daily', 'Tu dois choisir un rangement :', 'Chambre nickel', 'Bureau nickel'),
('daily_011', 'daily', 'Tu dois choisir une file d''attente :', 'Caisse lente', 'Bus en retard'),
('daily_012', 'daily', 'Tu dois choisir un oubli :', 'Oublier son portefeuille', 'Oublier ses ecouteurs'),
('daily_013', 'daily', 'Tu dois choisir un bruit :', 'Voisin bruyant', 'Reveil agressif'),
('daily_014', 'daily', 'Tu dois choisir une pause :', 'Sieste de 20 minutes', 'Balade de 20 minutes'),
('daily_015', 'daily', 'Tu dois choisir une tenue :', 'Trop habille', 'Pas assez habille'),
('daily_016', 'daily', 'Tu dois choisir une meteo :', 'Pluie fine toute la journee', 'Vent fort toute la journee'),
('daily_017', 'daily', 'Tu dois choisir un achat :', 'Objet utile moche', 'Objet beau inutile'),
('daily_018', 'daily', 'Tu dois choisir une panne :', 'Plus d''eau chaude', 'Plus de lumiere'),
('daily_019', 'daily', 'Tu dois choisir un planning :', 'Journee trop remplie', 'Journee trop vide'),
('daily_020', 'daily', 'Tu dois choisir une tache :', 'Faire les courses', 'Ranger les papiers'),
('daily_021', 'daily', 'Tu dois choisir un inconvenient :', 'Chaussettes mouillees', 'Cheveux mal coiffes'),
('daily_022', 'daily', 'Tu dois choisir une economie :', 'Economiser sur les sorties', 'Economiser sur les habits'),
('daily_023', 'daily', 'Tu dois choisir un voisinage :', 'Quartier vivant', 'Quartier silencieux'),
('daily_024', 'daily', 'Tu dois choisir une routine :', 'Petit rituel du matin', 'Petit rituel du soir'),
('daily_025', 'daily', 'Tu dois choisir un luxe simple :', 'Draps propres', 'Frigo plein'),

('powers_001', 'powers', 'Tu dois choisir un seul super-pouvoir :', 'Devenir invisible', 'Lire dans les pensees'),
('powers_002', 'powers', 'Tu dois choisir un pouvoir de deplacement :', 'Voler', 'Se teleporter'),
('powers_003', 'powers', 'Tu dois choisir un pouvoir sur le temps :', 'Voir le futur', 'Changer le passe'),
('powers_004', 'powers', 'Tu dois choisir un talent surnaturel :', 'Parler aux animaux', 'Parler toutes les langues'),
('powers_005', 'powers', 'Tu dois choisir un pouvoir de protection :', 'Guerir les autres', 'Etre immortel'),
('powers_006', 'powers', 'Tu dois choisir un pouvoir social :', 'Persuader n''importe qui', 'Detecter tous les mensonges'),
('powers_007', 'powers', 'Tu dois choisir un pouvoir mental :', 'Memoire parfaite', 'Apprendre instantanement'),
('powers_008', 'powers', 'Tu dois choisir un pouvoir physique :', 'Force surhumaine', 'Vitesse surhumaine'),
('powers_009', 'powers', 'Tu dois choisir un pouvoir discret :', 'Passer a travers les murs', 'Devenir minuscule'),
('powers_010', 'powers', 'Tu dois choisir un pouvoir elementaire :', 'Controler le feu', 'Controler l''eau'),
('powers_011', 'powers', 'Tu dois choisir une capacite magique :', 'Creer des portails', 'Arreter le temps 10 secondes'),
('powers_012', 'powers', 'Tu dois choisir un pouvoir de chance :', 'Chance parfaite', 'Trouver tout objet perdu'),
('powers_013', 'powers', 'Tu dois choisir une perception :', 'Voir dans le noir', 'Entendre a travers les murs'),
('powers_014', 'powers', 'Tu dois choisir une transformation :', 'Changer d''apparence', 'Copier une voix'),
('powers_015', 'powers', 'Tu dois choisir une competence :', 'Dessiner parfaitement', 'Chanter parfaitement'),
('powers_016', 'powers', 'Tu dois choisir un pouvoir d''argent :', 'Multiplier l''argent touche', 'Acheter sans payer'),
('powers_017', 'powers', 'Tu dois choisir un pouvoir de sommeil :', 'Dormir 2h et etre en forme', 'Ne jamais faire de cauchemar'),
('powers_018', 'powers', 'Tu dois choisir un pouvoir de creation :', 'Faire apparaitre de la nourriture', 'Reparer tous les objets'),
('powers_019', 'powers', 'Tu dois choisir une aide de vie :', 'Nettoyer par magie', 'Se souvenir de tout'),
('powers_020', 'powers', 'Tu dois choisir un pouvoir de controle :', 'Controler les reves', 'Controler la meteo'),
('powers_021', 'powers', 'Tu dois choisir une force sociale :', 'Ne jamais etre gene', 'Savoir toujours quoi dire'),
('powers_022', 'powers', 'Tu dois choisir un pouvoir de securite :', 'Voir les dangers a l''avance', 'Etre invincible 1 minute par jour'),
('powers_023', 'powers', 'Tu dois choisir un pouvoir bizarre :', 'Respirer sous l''eau', 'Manger sans jamais grossir'),
('powers_024', 'powers', 'Tu dois choisir un pouvoir de voyage :', 'Comprendre les cartes instantanement', 'Ne jamais se perdre'),
('powers_025', 'powers', 'Tu dois choisir un pouvoir de confort :', 'Temperature corporelle parfaite', 'Vetements toujours propres'),

('money_001', 'money', 'Tu dois choisir une richesse :', '1 million maintenant', '10000 euros par mois a vie'),
('money_002', 'money', 'Tu dois choisir un luxe :', 'Villa au bord de mer', 'Appartement en centre-ville'),
('money_003', 'money', 'Tu dois choisir un gros achat :', 'Voiture de luxe', 'Voyages illimites'),
('money_004', 'money', 'Tu dois choisir une vie :', 'Riche inconnu', 'Celebre mais moins riche'),
('money_005', 'money', 'Tu dois choisir une opportunite :', 'Gagner au loto', 'Creer une entreprise a succes'),
('money_006', 'money', 'Tu dois choisir une depense :', 'Restaurant tous les jours', 'Shopping tous les mois'),
('money_007', 'money', 'Tu dois choisir une securite :', 'Maison payee', 'Salaire garanti'),
('money_008', 'money', 'Tu dois choisir un cadeau :', 'Offrir un voyage', 'Offrir une voiture'),
('money_009', 'money', 'Tu dois choisir un style riche :', 'Luxe discret', 'Luxe visible'),
('money_010', 'money', 'Tu dois choisir une contrainte :', 'Riche sans Internet', 'Riche sans vacances'),
('money_011', 'money', 'Tu dois choisir une economie :', 'Plus jamais payer le loyer', 'Plus jamais payer la nourriture'),
('money_012', 'money', 'Tu dois choisir un reve :', 'Jet prive', 'Yacht'),
('money_013', 'money', 'Tu dois choisir une passion financee :', 'Studio de musique', 'Salle de cinema privee'),
('money_014', 'money', 'Tu dois choisir un investissement :', 'Immobilier', 'Bourse'),
('money_015', 'money', 'Tu dois choisir une chance :', 'Trouver 100 euros par jour', 'Gagner un concours par mois'),
('money_016', 'money', 'Tu dois choisir un travail :', 'Job passion mal paye', 'Job ennuyeux tres paye'),
('money_017', 'money', 'Tu dois choisir un achat fou :', 'Ile privee', 'Chateau'),
('money_018', 'money', 'Tu dois choisir une aide :', 'Payer les dettes de ta famille', 'Financer tes reves'),
('money_019', 'money', 'Tu dois choisir un bonus :', 'Cash immediat', 'Actions qui montent'),
('money_020', 'money', 'Tu dois choisir une limite :', 'Ne plus acheter de vetements', 'Ne plus commander a manger'),
('money_021', 'money', 'Tu dois choisir une carte magique :', 'Carte bancaire illimitee 1h par jour', 'Retrait de 200 euros par jour'),
('money_022', 'money', 'Tu dois choisir un patrimoine :', 'Bijoux rares', 'Montres rares'),
('money_023', 'money', 'Tu dois choisir une reputation :', 'Milliardaire discret', 'Influenceur riche'),
('money_024', 'money', 'Tu dois choisir une strategie :', 'Tout economiser', 'Tout investir'),
('money_025', 'money', 'Tu dois choisir un confort :', 'Chauffeur personnel', 'Chef cuisinier personnel'),

('impossible_001', 'impossible', 'Tu dois choisir une decision impossible :', 'Sauver une personne proche', 'Sauver 100 inconnus'),
('impossible_002', 'impossible', 'Tu dois choisir une souffrance sociale :', 'Etre aime mais pas respecte', 'Etre respecte mais pas aime'),
('impossible_003', 'impossible', 'Tu dois choisir une connaissance lourde :', 'Savoir quand tu vas mourir', 'Savoir comment tu vas mourir'),
('impossible_004', 'impossible', 'Tu dois choisir une regle de vie :', 'Ne jamais mentir', 'Dire toutes tes pensees'),
('impossible_005', 'impossible', 'Tu dois choisir une perte :', 'Perdre tous tes souvenirs', 'Perdre toutes tes photos'),
('impossible_006', 'impossible', 'Tu dois choisir une verite :', 'Connaitre chaque mensonge qu''on te dit', 'Voir chaque fois que tu mens'),
('impossible_007', 'impossible', 'Tu dois choisir une responsabilite :', 'Decider pour ta ville', 'Decider pour ta famille'),
('impossible_008', 'impossible', 'Tu dois choisir une solitude :', 'Un an seul mais riche', 'Un an accompagne mais pauvre'),
('impossible_009', 'impossible', 'Tu dois choisir une memoire :', 'Tout oublier chaque annee', 'Ne rien oublier jamais'),
('impossible_010', 'impossible', 'Tu dois choisir une priorite :', 'Justice absolue', 'Bonheur absolu'),
('impossible_011', 'impossible', 'Tu dois choisir une reputation :', 'Etre accuse a tort', 'Etre coupable cache'),
('impossible_012', 'impossible', 'Tu dois choisir un sacrifice :', 'Reussir mais perdre tes amis', 'Garder tes amis mais echouer'),
('impossible_013', 'impossible', 'Tu dois choisir une limite :', 'Ne plus ressentir la peur', 'Ne plus ressentir la honte'),
('impossible_014', 'impossible', 'Tu dois choisir un dilemme moral :', 'Punir un innocent pour sauver dix personnes', 'Laisser dix personnes subir les consequences'),
('impossible_015', 'impossible', 'Tu dois choisir une vie :', 'Courte mais incroyable', 'Longue mais banale'),
('impossible_016', 'impossible', 'Tu dois choisir une information :', 'Savoir ce que tout le monde pense de toi', 'Ne jamais savoir quand on te critique'),
('impossible_017', 'impossible', 'Tu dois choisir un monde :', 'Paix sans liberte', 'Liberte sans paix'),
('impossible_018', 'impossible', 'Tu dois choisir une consequence :', 'Gagner en blessant quelqu''un', 'Perdre en protegeant quelqu''un'),
('impossible_019', 'impossible', 'Tu dois choisir une promesse :', 'Toujours tenir parole', 'Toujours dire ce qui est juste'),
('impossible_020', 'impossible', 'Tu dois choisir une peur collective :', 'Etre oublie', 'Etre deteste'),
('impossible_021', 'impossible', 'Tu dois choisir une verite familiale :', 'Apprendre un secret de famille', 'Garder un secret de famille'),
('impossible_022', 'impossible', 'Tu dois choisir une seconde chance :', 'Revivre ton pire jour pour le changer', 'Revivre ton meilleur jour sans rien changer'),
('impossible_023', 'impossible', 'Tu dois choisir un pouvoir dangereux :', 'Controler une personne une fois', 'Effacer un souvenir a quelqu''un'),
('impossible_024', 'impossible', 'Tu dois choisir un choix irreversible :', 'Changer de pays pour toujours', 'Rester dans la meme ville pour toujours'),
('impossible_025', 'impossible', 'Tu dois choisir une fin de conflit :', 'Avoir raison seul', 'Avoir tort avec tout le monde'),

('awkward_001', 'awkward', 'Tu dois choisir une honte publique :', 'Tomber devant tout le monde', 'Envoyer un message au mauvais groupe'),
('awkward_002', 'awkward', 'Tu dois choisir une scene genee :', 'Chanter devant une salle', 'Danser seul sur scene'),
('awkward_003', 'awkward', 'Tu dois choisir une fuite privee :', 'Historique visible', 'Messages prives visibles'),
('awkward_004', 'awkward', 'Tu dois choisir un moment malaise :', 'Rire au mauvais moment', 'Parler trop fort sans le vouloir'),
('awkward_005', 'awkward', 'Tu dois choisir une erreur sociale :', 'Appeler un prof maman', 'Dire bonjour deux fois'),
('awkward_006', 'awkward', 'Tu dois choisir une gene physique :', 'Tache sur le tee-shirt', 'Braguette ouverte'),
('awkward_007', 'awkward', 'Tu dois choisir une confusion :', 'Faire coucou a un inconnu', 'Repondre a quelqu''un qui ne te parlait pas'),
('awkward_008', 'awkward', 'Tu dois choisir un bruit genant :', 'Ventre qui gargouille', 'Chaise qui grince'),
('awkward_009', 'awkward', 'Tu dois choisir un fail de presentation :', 'Trou de memoire', 'Diapo avec faute enorme'),
('awkward_010', 'awkward', 'Tu dois choisir une honte numerique :', 'Like accidentel sur vieille photo', 'Story publiee sans faire expres'),
('awkward_011', 'awkward', 'Tu dois choisir un silence :', 'Blague sans rire', 'Question sans reponse'),
('awkward_012', 'awkward', 'Tu dois choisir une confusion de prenom :', 'Se tromper de prenom', 'Oublier un prenom important'),
('awkward_013', 'awkward', 'Tu dois choisir un moment repas :', 'Renverser son verre', 'Avoir de la sauce sur le visage'),
('awkward_014', 'awkward', 'Tu dois choisir un probleme de voix :', 'Voix qui deraille', 'Bafouiller toute une phrase'),
('awkward_015', 'awkward', 'Tu dois choisir une situation de transport :', 'Rater son arret', 'Se coincer dans les portes'),
('awkward_016', 'awkward', 'Tu dois choisir une honte en appel :', 'Micro ouvert sans savoir', 'Camera allumee sans savoir'),
('awkward_017', 'awkward', 'Tu dois choisir un malentendu :', 'Repondre trop vite', 'Envoyer un emoji bizarre'),
('awkward_018', 'awkward', 'Tu dois choisir une tenue ratee :', 'Deux chaussures differentes', 'Etiquette visible'),
('awkward_019', 'awkward', 'Tu dois choisir un moment de panique :', 'Oublier pourquoi tu es entre dans une piece', 'Chercher ton telephone alors qu''il est dans ta main'),
('awkward_020', 'awkward', 'Tu dois choisir une gaffe orale :', 'Dire un mot de travers', 'Melanger deux expressions'),
('awkward_021', 'awkward', 'Tu dois choisir une honte sportive :', 'Rater un tir facile', 'Tomber en courant'),
('awkward_022', 'awkward', 'Tu dois choisir une gene au restaurant :', 'Carte bancaire refusee', 'Commander le mauvais plat'),
('awkward_023', 'awkward', 'Tu dois choisir un malaise de groupe :', 'Etre le seul deguise', 'Etre le seul pas deguise'),
('awkward_024', 'awkward', 'Tu dois choisir un fail de message :', 'Autocorrect embarrassant', 'Reponse envoyee trop tard'),
('awkward_025', 'awkward', 'Tu dois choisir une honte classique :', 'Marcher dans une porte vitree', 'Serrer une main qui n''etait pas tendue'),

('internet_001', 'internet', 'Tu dois choisir une culture web :', 'Plus jamais memes', 'Plus jamais musique'),
('internet_002', 'internet', 'Tu dois choisir une celebrite digitale :', 'Connu sur TikTok', 'Riche mais inconnu'),
('internet_003', 'internet', 'Tu dois choisir une vie en ligne :', '1 million d''abonnes sans amis proches', '5 amis fideles sans abonnes'),
('internet_004', 'internet', 'Tu dois choisir une appli a supprimer :', 'Supprimer Instagram', 'Supprimer TikTok'),
('internet_005', 'internet', 'Tu dois choisir une peur numerique :', 'Perdre ton compte principal', 'Perdre toutes tes sauvegardes'),
('internet_006', 'internet', 'Tu dois choisir une habitude :', 'Regarder des threads', 'Regarder des lives'),
('internet_007', 'internet', 'Tu dois choisir un contenu viral :', 'Challenge drole', 'Debat explosif'),
('internet_008', 'internet', 'Tu dois choisir une identite :', 'Pseudo connu', 'Photo de profil connue'),
('internet_009', 'internet', 'Tu dois choisir une communaute :', 'Serveur Discord actif', 'Groupe prive Instagram'),
('internet_010', 'internet', 'Tu dois choisir un format long :', 'Podcast', 'Video YouTube de 40 minutes'),
('internet_011', 'internet', 'Tu dois choisir une recommandation :', 'Algorithme parfait', 'Abonnements parfaits'),
('internet_012', 'internet', 'Tu dois choisir un bug :', 'Compte shadowban', 'Commentaires desactives'),
('internet_013', 'internet', 'Tu dois choisir un mode de vie :', 'Digital detox un mois', 'Internet illimite mais lent'),
('internet_014', 'internet', 'Tu dois choisir une reputation web :', 'Etre connu pour une blague', 'Etre connu pour un avis'),
('internet_015', 'internet', 'Tu dois choisir une archive :', 'Supprimer tous tes anciens posts', 'Garder tout pour toujours'),
('internet_016', 'internet', 'Tu dois choisir un abonnement :', 'Netflix', 'Prime Video'),
('internet_017', 'internet', 'Tu dois choisir un outil :', 'Google', 'ChatGPT'),
('internet_018', 'internet', 'Tu dois choisir une passion web :', 'Streams gaming', 'Videos reaction'),
('internet_019', 'internet', 'Tu dois choisir une notification :', '100 likes', '1 message important'),
('internet_020', 'internet', 'Tu dois choisir une panne :', 'Plus de reseau mobile', 'Plus de Wi-Fi'),
('internet_021', 'internet', 'Tu dois choisir une epoque internet :', 'YouTube 2010', 'TikTok 2026'),
('internet_022', 'internet', 'Tu dois choisir un contenu educatif :', 'Tuto rapide', 'Article detaille'),
('internet_023', 'internet', 'Tu dois choisir une image en ligne :', 'Feed parfait', 'Profil authentique'),
('internet_024', 'internet', 'Tu dois choisir une sauvegarde :', 'Cloud', 'Disque dur externe'),
('internet_025', 'internet', 'Tu dois choisir une regle :', 'Pas de telephone au lit', 'Pas de telephone a table');

select public.seed_question_votes(true);
